# Generated by Django 5.2 on 2025-06-21 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='pg_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.owner'),
        ),
    ]
